#!/bin/bash/

~/Documents/Programs/bbmap/bbduk.sh in=GA1.fq out=trim_GA1.fq ref=primer1.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA2.fq out=trim_GA2.fq ref=primer2.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA3.fq out=trim_GA3.fq ref=primer3.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA4.fq out=trim_GA4.fq ref=primer4.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA5.fq out=trim_GA5.fq ref=primer5.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA6.fq out=trim_GA6.fq ref=primer6.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA7.fq out=trim_GA7.fq ref=primer7.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA8.fq out=trim_GA8.fq ref=primer8.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA9.fq out=trim_GA9.fq ref=primer9.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA10.fq out=trim_GA10.fq ref=primer10.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA11.fq out=trim_GA11.fq ref=primer11.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA12.fq out=trim_GA12.fq ref=primer12.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA13.fq out=trim_GA13.fq ref=primer13.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA14.fq out=trim_GA14.fq ref=primer14.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA15.fq out=trim_GA15.fq ref=primer15.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA16.fq out=trim_GA16.fq ref=primer16.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA17.fq out=trim_GA17.fq ref=primer17.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA18.fq out=trim_GA18.fq ref=primer18.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA19.fq out=trim_GA19.fq ref=primer19.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA20.fq out=trim_GA20.fq ref=primer20.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA21.fq out=trim_GA21.fq ref=primer21.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA22.fq out=trim_GA22.fq ref=primer22.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA23.fq out=trim_GA23.fq ref=primer23.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA24.fq out=trim_GA24.fq ref=primer24.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA25.fq out=trim_GA25.fq ref=primer25.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA26.fq out=trim_GA26.fq ref=primer26.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA27.fq out=trim_GA27.fq ref=primer27.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA28.fq out=trim_GA28.fq ref=primer28.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA29.fq out=trim_GA29.fq ref=primer29.fa k=18 restrictleft=18 ktrim=l
~/Documents/Programs/bbmap/bbduk.sh in=GA30.fq out=trim_GA30.fq ref=primer30.fa k=18 restrictleft=18 ktrim=l
